name: Modificar Cliente

on:
  workflow_dispatch:
    inputs:
      numero_cliente:
        description: 'Número del cliente a modificar (ej. C001)'
        required: true

jobs:
  notify_team:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar equipos
        run: |
          echo "[CLIENTE MODIFICADO] Número: ${{ github.event.inputs.numero_cliente }}. Notificando a DesarrolladoresSky, EquipoITSky, AtencionClienteSky."